name: Lint

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FORCE_COLOR: "1"

jobs:
  ruff:
    name: Lint using Ruff
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3"
    - name: Install pip
      run: python -m pip install --upgrade pip
    - name: Install Ruff
      run: python -m pip install "ruff==0.5.5"
    - name: Lint with Ruff
      run: ruff check docutils --output-format github

  flake8:
    name: Lint using flake8
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3"
    - name: Install pip
      run: python -m pip install --upgrade pip
    - name: Install flake8
      run: python -m pip install --upgrade flake8
    - name: Run flake8
      run: flake8 docutils

  twine:
    name: Check packaging using twine
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade twine build
    - name: Lint with twine
      run: |
        cd docutils
        python -m build
        twine check --strict dist/*
